# Generated by Django 4.2.2 on 2023-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_itens_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pagamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
