# Generated by Django 4.2.2 on 2023-06-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_aluno_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='pagamento',
        ),
    ]
